library(tidyverse)
library(dplyr)
# replace address with your own
results <- read.csv("C:/Users/Darima/Desktop/RL/RL1/results.csv")
rewards <- read.csv("C:/Users/Darima/Desktop/RL/RL1/rewards.csv")
normal_results <- filter(results, bandit == "normal_dist")
binary_results <- filter(results, bandit == "bernoulli_dist")
norm_percentage <- ggplot(normal_results) + geom_smooth(mapping = aes(x = selection, y = optimal_percentage, color = algorithm))
print(norm_percentage + ggtitle("Percentage of optimal choices in normal distribution") + theme(legend.position = c(0.85,0.2)))
binary_percentage <- ggplot(binary_results) + geom_smooth(mapping = aes(x = selection, y = optimal_percentage, color = algorithm))
print(binary_percentage + ggtitle("Percentage of optimal choices in Bernoulli distribution") + theme(legend.position = c(0.85,0.2)))
norm_ave <- ggplot(normal_results) + geom_smooth(mapping = aes(x = selection, y = average_reward, color = algorithm))
print(norm_ave + ggtitle("Average rewards in normal distribution") + theme(legend.position = c(0.85,0.2)))
binary_ave <- ggplot(binary_results) + geom_smooth(mapping = aes(x = selection, y = average_reward, color = algorithm))
print(binary_ave + ggtitle("Average rewards in Bernoulli distribution") + theme(legend.position = c(0.85,0.2)))

normal_rewards <- filter(rewards, bandit == "normal_dist")
bernoulli_rewards <- filter(rewards, bandit == "bernoulli_dist")

mean(normal_rewards$total_reward[normal_rewards$algorithm == "eps_greedy"])
mean(normal_rewards$total_reward[normal_rewards$algorithm == "optimistic"])
mean(normal_rewards$total_reward[normal_rewards$algorithm == "reinforcement_comp"])
mean(normal_rewards$total_reward[normal_rewards$algorithm == "UCB"])
mean(bernoulli_rewards$total_reward[bernoulli_rewards$algorithm == "eps_greedy"])
mean(bernoulli_rewards$total_reward[bernoulli_rewards$algorithm == "optimistic"])
mean(bernoulli_rewards$total_reward[bernoulli_rewards$algorithm == "reinforcement_comp"])
mean(bernoulli_rewards$total_reward[bernoulli_rewards$algorithm == "UCB"])

sd(normal_rewards$total_reward[normal_rewards$algorithm=="eps_greedy"])
sd(normal_rewards$total_reward[normal_rewards$algorithm=="optimistic"])
sd(normal_rewards$total_reward[normal_rewards$algorithm=="reinforcement_comp"])
sd(normal_rewards$total_reward[normal_rewards$algorithm=="UCB"])
sd(bernoulli_rewards$total_reward[bernoulli_rewards$algorithm=="eps_greedy"])
sd(bernoulli_rewards$total_reward[bernoulli_rewards$algorithm=="optimistic"])
sd(bernoulli_rewards$total_reward[bernoulli_rewards$algorithm=="reinforcement_comp"])
sd(bernoulli_rewards$total_reward[bernoulli_rewards$algorithm=="UCB"])